package com.elderlycare.mapper;

import com.elderlycare.model.CareTaskRecord;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface CareTaskRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table care_task_record
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    @Delete({
        "delete from care_task_record",
        "where record_id = #{recordId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table care_task_record
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    @Insert({
        "insert into care_task_record (record_id, plan_id, ",
        "nurse_id, executed_at, ",
        "task_detail)",
        "values (#{recordId,jdbcType=BIGINT}, #{planId,jdbcType=BIGINT}, ",
        "#{nurseId,jdbcType=BIGINT}, #{executedAt,jdbcType=TIMESTAMP}, ",
        "#{taskDetail,jdbcType=LONGVARCHAR})"
    })
    int insert(CareTaskRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table care_task_record
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    @Select({
        "select",
        "record_id, plan_id, nurse_id, executed_at, task_detail",
        "from care_task_record",
        "where record_id = #{recordId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="record_id", property="recordId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="plan_id", property="planId", jdbcType=JdbcType.BIGINT),
        @Result(column="nurse_id", property="nurseId", jdbcType=JdbcType.BIGINT),
        @Result(column="executed_at", property="executedAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="task_detail", property="taskDetail", jdbcType=JdbcType.LONGVARCHAR)
    })
    CareTaskRecord selectByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table care_task_record
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    @Select({
        "select",
        "record_id, plan_id, nurse_id, executed_at, task_detail",
        "from care_task_record"
    })
    @Results({
        @Result(column="record_id", property="recordId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="plan_id", property="planId", jdbcType=JdbcType.BIGINT),
        @Result(column="nurse_id", property="nurseId", jdbcType=JdbcType.BIGINT),
        @Result(column="executed_at", property="executedAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="task_detail", property="taskDetail", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<CareTaskRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table care_task_record
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    @Update({
        "update care_task_record",
        "set plan_id = #{planId,jdbcType=BIGINT},",
          "nurse_id = #{nurseId,jdbcType=BIGINT},",
          "executed_at = #{executedAt,jdbcType=TIMESTAMP},",
          "task_detail = #{taskDetail,jdbcType=LONGVARCHAR}",
        "where record_id = #{recordId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(CareTaskRecord record);

    /**
     * 查询某个护理计划下的所有执行记录
     */
    @Select({
      "SELECT",
      "  record_id, plan_id, nurse_id, task_detail, executed_at",
      "FROM care_task_record",
      "WHERE plan_id = #{planId}",
      "ORDER BY executed_at DESC"
    })
    @Results({
      @Result(column="record_id",  property="recordId",  jdbcType=JdbcType.BIGINT, id=true),
      @Result(column="plan_id",    property="planId",     jdbcType=JdbcType.BIGINT),
      @Result(column="nurse_id",   property="nurseId",    jdbcType=JdbcType.BIGINT),
      @Result(column="task_detail",property="taskDetail", jdbcType=JdbcType.VARCHAR),
      @Result(column="executed_at",property="executedAt", jdbcType=JdbcType.TIMESTAMP)
    })
    List<CareTaskRecord> selectByPlanId(@Param("planId") Long planId);
}
