package com.elderlycare.mapper;

import com.elderlycare.model.Institution;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface InstitutionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    @Delete({
        "delete from institution",
        "where institution_id = #{institutionId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long institutionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    @Insert({
        "insert into institution (institution_id, name, ",
        "address, contact, ",
        "status, description)",
        "values (#{institutionId,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{contact,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=VARCHAR}, #{description,jdbcType=LONGVARCHAR})"
    })
    int insert(Institution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    @Select({
        "select",
        "institution_id, name, address, contact, status, description",
        "from institution",
        "where institution_id = #{institutionId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="institution_id", property="institutionId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="contact", property="contact", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.LONGVARCHAR)
    })
    Institution selectByPrimaryKey(Long institutionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    @Select({
        "select",
        "institution_id, name, address, contact, status, description",
        "from institution"
    })
    @Results({
        @Result(column="institution_id", property="institutionId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="contact", property="contact", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<Institution> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    @Update({
        "update institution",
        "set name = #{name,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "contact = #{contact,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=LONGVARCHAR}",
        "where institution_id = #{institutionId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Institution record);
}
