package com.elderlycare.model;

import java.math.BigDecimal;
import java.util.Date;

public class Billing {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column billing.bill_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Long billId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column billing.elder_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Long elderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column billing.item_name
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column billing.amount
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column billing.billing_month
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String billingMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column billing.status
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column billing.paid_at
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Date paidAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column billing.bill_id
     *
     * @return the value of billing.bill_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Long getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column billing.bill_id
     *
     * @param billId the value for billing.bill_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setBillId(Long billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column billing.elder_id
     *
     * @return the value of billing.elder_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Long getElderId() {
        return elderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column billing.elder_id
     *
     * @param elderId the value for billing.elder_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setElderId(Long elderId) {
        this.elderId = elderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column billing.item_name
     *
     * @return the value of billing.item_name
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column billing.item_name
     *
     * @param itemName the value for billing.item_name
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column billing.amount
     *
     * @return the value of billing.amount
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column billing.amount
     *
     * @param amount the value for billing.amount
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column billing.billing_month
     *
     * @return the value of billing.billing_month
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getBillingMonth() {
        return billingMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column billing.billing_month
     *
     * @param billingMonth the value for billing.billing_month
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setBillingMonth(String billingMonth) {
        this.billingMonth = billingMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column billing.status
     *
     * @return the value of billing.status
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column billing.status
     *
     * @param status the value for billing.status
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column billing.paid_at
     *
     * @return the value of billing.paid_at
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Date getPaidAt() {
        return paidAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column billing.paid_at
     *
     * @param paidAt the value for billing.paid_at
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setPaidAt(Date paidAt) {
        this.paidAt = paidAt;
    }
}