package com.elderlycare.model;

import java.util.Date;

public class CarePlan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column care_plan.plan_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Long planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column care_plan.elder_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Long elderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column care_plan.level
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column care_plan.created_at
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column care_plan.status
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column care_plan.task
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String task;

    private boolean archived = false;

    public boolean isArchived() {
        return archived;
    }

    public void setArchived(boolean archived) {
        this.archived = archived;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column care_plan.plan_id
     *
     * @return the value of care_plan.plan_id
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Long getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column care_plan.plan_id
     *
     * @param planId the value for care_plan.plan_id
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setPlanId(Long planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column care_plan.elder_id
     *
     * @return the value of care_plan.elder_id
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Long getElderId() {
        return elderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column care_plan.elder_id
     *
     * @param elderId the value for care_plan.elder_id
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setElderId(Long elderId) {
        this.elderId = elderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column care_plan.level
     *
     * @return the value of care_plan.level
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column care_plan.level
     *
     * @param level the value for care_plan.level
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column care_plan.created_at
     *
     * @return the value of care_plan.created_at
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column care_plan.created_at
     *
     * @param createdAt the value for care_plan.created_at
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column care_plan.status
     *
     * @return the value of care_plan.status
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column care_plan.status
     *
     * @param status the value for care_plan.status
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column care_plan.task
     *
     * @return the value of care_plan.task
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getTask() {
        return task;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column care_plan.task
     *
     * @param task the value for care_plan.task
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setTask(String task) {
        this.task = task;
    }
}
