package com.elderlycare.model;

import java.util.Date;

public class CareTaskRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column care_task_record.record_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Long recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column care_task_record.plan_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Long planId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column care_task_record.nurse_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Long nurseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column care_task_record.executed_at
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Date executedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column care_task_record.task_detail
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String taskDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column care_task_record.record_id
     *
     * @return the value of care_task_record.record_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Long getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column care_task_record.record_id
     *
     * @param recordId the value for care_task_record.record_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column care_task_record.plan_id
     *
     * @return the value of care_task_record.plan_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Long getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column care_task_record.plan_id
     *
     * @param planId the value for care_task_record.plan_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setPlanId(Long planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column care_task_record.nurse_id
     *
     * @return the value of care_task_record.nurse_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Long getNurseId() {
        return nurseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column care_task_record.nurse_id
     *
     * @param nurseId the value for care_task_record.nurse_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setNurseId(Long nurseId) {
        this.nurseId = nurseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column care_task_record.executed_at
     *
     * @return the value of care_task_record.executed_at
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Date getExecutedAt() {
        return executedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column care_task_record.executed_at
     *
     * @param executedAt the value for care_task_record.executed_at
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setExecutedAt(Date executedAt) {
        this.executedAt = executedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column care_task_record.task_detail
     *
     * @return the value of care_task_record.task_detail
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getTaskDetail() {
        return taskDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column care_task_record.task_detail
     *
     * @param taskDetail the value for care_task_record.task_detail
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setTaskDetail(String taskDetail) {
        this.taskDetail = taskDetail;
    }
}