package com.elderlycare.model;

import org.springframework.stereotype.Repository;

@Repository
public class Elder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elder.elder_id
     *
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    private Long elderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elder.name
     *
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elder.gender
     *
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elder.id_card
     *
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elder.age
     *
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elder.contact
     *
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elder.address
     *
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elder.emergency_contact
     *
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    private String emergencyContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elder.institution_id
     *
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    private Long institutionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elder.allergies
     *
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    private String allergies;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elder.medical_history
     *
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    private String medicalHistory;

    private boolean archived = false;   // 新增

    public boolean isArchived() {
        return archived;
    }

    public void setArchived(boolean archived) {
        this.archived = archived;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elder.elder_id
     *
     * @return the value of elder.elder_id
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public Long getElderId() {
        return elderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elder.elder_id
     *
     * @param elderId the value for elder.elder_id
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public void setElderId(Long elderId) {
        this.elderId = elderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elder.name
     *
     * @return the value of elder.name
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elder.name
     *
     * @param name the value for elder.name
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elder.gender
     *
     * @return the value of elder.gender
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elder.gender
     *
     * @param gender the value for elder.gender
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elder.id_card
     *
     * @return the value of elder.id_card
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elder.id_card
     *
     * @param idCard the value for elder.id_card
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elder.age
     *
     * @return the value of elder.age
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elder.age
     *
     * @param age the value for elder.age
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elder.contact
     *
     * @return the value of elder.contact
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elder.contact
     *
     * @param contact the value for elder.contact
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elder.address
     *
     * @return the value of elder.address
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elder.address
     *
     * @param address the value for elder.address
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elder.emergency_contact
     *
     * @return the value of elder.emergency_contact
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public String getEmergencyContact() {
        return emergencyContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elder.emergency_contact
     *
     * @param emergencyContact the value for elder.emergency_contact
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public void setEmergencyContact(String emergencyContact) {
        this.emergencyContact = emergencyContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elder.institution_id
     *
     * @return the value of elder.institution_id
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public Long getInstitutionId() {
        return institutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elder.institution_id
     *
     * @param institutionId the value for elder.institution_id
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public void setInstitutionId(Long institutionId) {
        this.institutionId = institutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elder.allergies
     *
     * @return the value of elder.allergies
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public String getAllergies() {
        return allergies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elder.allergies
     *
     * @param allergies the value for elder.allergies
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public void setAllergies(String allergies) {
        this.allergies = allergies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elder.medical_history
     *
     * @return the value of elder.medical_history
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public String getMedicalHistory() {
        return medicalHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elder.medical_history
     *
     * @param medicalHistory the value for elder.medical_history
     * @mbg.generated Sun Apr 27 14:56:17 HKT 2025
     */
    public void setMedicalHistory(String medicalHistory) {
        this.medicalHistory = medicalHistory;
    }
}
