package com.elderlycare.model;

import java.math.BigDecimal;
import java.util.Date;

public class HealthRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_record.record_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Long recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_record.elder_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Long elderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_record.blood_pressure
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String bloodPressure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_record.blood_sugar
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private BigDecimal bloodSugar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_record.record_date
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Date recordDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_record.medication
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String medication;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_record.record_id
     *
     * @return the value of health_record.record_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Long getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_record.record_id
     *
     * @param recordId the value for health_record.record_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_record.elder_id
     *
     * @return the value of health_record.elder_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Long getElderId() {
        return elderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_record.elder_id
     *
     * @param elderId the value for health_record.elder_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setElderId(Long elderId) {
        this.elderId = elderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_record.blood_pressure
     *
     * @return the value of health_record.blood_pressure
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getBloodPressure() {
        return bloodPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_record.blood_pressure
     *
     * @param bloodPressure the value for health_record.blood_pressure
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setBloodPressure(String bloodPressure) {
        this.bloodPressure = bloodPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_record.blood_sugar
     *
     * @return the value of health_record.blood_sugar
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public BigDecimal getBloodSugar() {
        return bloodSugar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_record.blood_sugar
     *
     * @param bloodSugar the value for health_record.blood_sugar
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setBloodSugar(BigDecimal bloodSugar) {
        this.bloodSugar = bloodSugar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_record.record_date
     *
     * @return the value of health_record.record_date
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Date getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_record.record_date
     *
     * @param recordDate the value for health_record.record_date
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_record.medication
     *
     * @return the value of health_record.medication
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getMedication() {
        return medication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_record.medication
     *
     * @param medication the value for health_record.medication
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setMedication(String medication) {
        this.medication = medication;
    }
}