package com.elderlycare.model;

public class Institution {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution.institution_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Long institutionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution.name
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution.address
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution.contact
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution.status
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution.description
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institution.institution_id
     *
     * @return the value of institution.institution_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Long getInstitutionId() {
        return institutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institution.institution_id
     *
     * @param institutionId the value for institution.institution_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setInstitutionId(Long institutionId) {
        this.institutionId = institutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institution.name
     *
     * @return the value of institution.name
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institution.name
     *
     * @param name the value for institution.name
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institution.address
     *
     * @return the value of institution.address
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institution.address
     *
     * @param address the value for institution.address
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institution.contact
     *
     * @return the value of institution.contact
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institution.contact
     *
     * @param contact the value for institution.contact
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institution.status
     *
     * @return the value of institution.status
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institution.status
     *
     * @param status the value for institution.status
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institution.description
     *
     * @return the value of institution.description
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institution.description
     *
     * @param description the value for institution.description
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setDescription(String description) {
        this.description = description;
    }
}