package com.elderlycare.model;

public class RelativeElder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relative_elder.id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relative_elder.user_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relative_elder.elder_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Long elderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relative_elder.relation
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String relation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relative_elder.id
     *
     * @return the value of relative_elder.id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relative_elder.id
     *
     * @param id the value for relative_elder.id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relative_elder.user_id
     *
     * @return the value of relative_elder.user_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relative_elder.user_id
     *
     * @param userId the value for relative_elder.user_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relative_elder.elder_id
     *
     * @return the value of relative_elder.elder_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Long getElderId() {
        return elderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relative_elder.elder_id
     *
     * @param elderId the value for relative_elder.elder_id
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setElderId(Long elderId) {
        this.elderId = elderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relative_elder.relation
     *
     * @return the value of relative_elder.relation
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relative_elder.relation
     *
     * @param relation the value for relative_elder.relation
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setRelation(String relation) {
        this.relation = relation;
    }
}