package com.elderlycare.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uid
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mail
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.url
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.screenName
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String screenname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.activated
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private Date activated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.photo
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    private String photo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uid
     *
     * @return the value of user.uid
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uid
     *
     * @param uid the value for user.uid
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mail
     *
     * @return the value of user.mail
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mail
     *
     * @param mail the value for user.mail
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.url
     *
     * @return the value of user.url
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.url
     *
     * @param url the value for user.url
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.screenName
     *
     * @return the value of user.screenName
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getScreenname() {
        return screenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.screenName
     *
     * @param screenname the value for user.screenName
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setScreenname(String screenname) {
        this.screenname = screenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.created
     *
     * @return the value of user.created
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.created
     *
     * @param created the value for user.created
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.activated
     *
     * @return the value of user.activated
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public Date getActivated() {
        return activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.activated
     *
     * @param activated the value for user.activated
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setActivated(Date activated) {
        this.activated = activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role
     *
     * @return the value of user.role
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role
     *
     * @param role the value for user.role
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.photo
     *
     * @return the value of user.photo
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.photo
     *
     * @param photo the value for user.photo
     *
     * @mbg.generated Wed May 07 09:58:34 HKT 2025
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }
}